services:
    _defaults:
        autowire: true
        autoconfigure: true

    c975L\ServicesBundle\Service\:
        resource: '../../Service/*'

    c975L\ServicesBundle\Twig\:
        resource: '../../Twig/*'
