services:
    _defaults:
        autowire: true
        autoconfigure: true

    c975L\ServicesBundle\Service\:
        resource: '../src/Service/*'

    c975L\ServicesBundle\Twig\:
        resource: '../src/Twig/*'
